services:
  postgres:
    ports:
      - '5432:${DATABASE_PORT}'
    environment:
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_DB=${DATABASE_NAME}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
    image: 'postgres'